[package]
name = "colink-protocol-storage-macro-fallback"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colink = "0.3.9"
tokio = "1.28.2"
tracing = "0.1.37"
